name: CI/CD TLS Deployment  

# Trigger the workflow on push to master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t anandh15/wisecow:latest .
          docker push anandh15/wisecow:latest

      - name: Start Minikube
        run: |
          sudo minikube start --driver=docker
          sudo minikube status
          # Export kubeconfig so kubectl uses the right cluster
          mkdir -p $HOME/.kube
          sudo minikube kubectl -- config view --raw > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          kubectl cluster-info

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/wisecow-deployment.yaml --validate=false
          kubectl apply -f kubernetes/wisecow-service.yaml --validate=false
          kubectl apply -f wisecow-ingress.yaml --validate=false